import expresss from "express";
import { EquipamientoController } from "../controllers/EquipamientoController.js";
import { authMiddleware } from "../../../middlewares/authMiddleware.js";
const router = expresss.Router();
router.use(authMiddleware);
router.get("/", EquipamientoController.listar);
router.get("/:id", EquipamientoController.obtenerPorId);
router.post("/", EquipamientoController.crear);
router.put("/:id", EquipamientoController.actualizar);
router.delete("/:id", EquipamientoController.eliminar);
export default router;